"""
Sudha AI - Real Whisper to Cognitive Experiment Integration

Step 64-B

Validates the real runtime path:

Real Audio
    ↓
Whisper.cpp CLI
    ↓
WhisperCLIBackend
    ↓
SpeechRecognitionEngine
    ↓
Real Transcription
    ↓
Cognitive Experiment
    ↓
Hypothesis Selection
    ↓
Prediction
    ↓
Observed Outcome
    ↓
Prediction Error
    ↓
Hypothesis-Specific Learning
    ↓
NEXT CYCLE
    ↓
Changed Prediction

This test intentionally uses:

- real whisper.cpp executable
- real tiny.en model
- real JFK sample audio
- real CognitiveExperimentEngine
- real AdaptivePredictor learning

No deterministic speech mock is used at the
speech-recognition boundary.

The observed outcome used for the cognitive experiment
is explicitly derived from the real Whisper transcription.
It is never generated by the predictor itself.
"""

from pathlib import Path

from core.cognitive_experiment import (
    CognitiveExperimentEngine
)
from core.cognitive_pipeline import CognitivePipeline
from core.hypothesis import HypothesisEngine
from core.hypothesis_planner import (
    HypothesisPlanningEngine
)
from core.speech_recognition import (
    SpeechRecognitionEngine
)
from core.whisper_cli_backend import (
    WhisperCLIBackend
)


ROOT = Path(__file__).resolve().parents[1]

WHISPER_EXECUTABLE = (
    ROOT
    / "whisper.cpp"
    / "build"
    / "bin"
    / "whisper-cli"
)

WHISPER_MODEL = (
    ROOT
    / "whisper.cpp"
    / "models"
    / "ggml-tiny.en.bin"
)

JFK_AUDIO = (
    ROOT
    / "whisper.cpp"
    / "samples"
    / "jfk.wav"
)


class RealSpeechOutcomeExperiment:
    """
    Experiment dependency used to expose an explicit
    observed outcome to the cognitive experiment engine.

    The outcome is derived from the real Whisper
    transcription supplied during construction.

    No prediction is used to generate the outcome.
    """

    def __init__(self, transcription):
        if not isinstance(
            transcription,
            str
        ):
            raise TypeError(
                "transcription must be a string"
            )

        if not transcription.strip():
            raise ValueError(
                "transcription cannot be empty"
            )

        self.transcription = transcription

        self.observed_value = (
            len(transcription)
            + 20
        )

        self.received_hypothesis = None

    def run(
        self,
        observation,
        hypothesis=None
    ):
        """
        Return the explicit observed outcome.

        The outcome depends only on the real
        Whisper transcription and not on the
        current prediction.
        """

        self.received_hypothesis = (
            hypothesis
        )

        return self.observed_value


def create_real_speech_engine():
    """
    Create the real Whisper speech-recognition engine.

    This helper performs environment validation and
    dependency construction. It does not mock Whisper.
    """

    assert WHISPER_EXECUTABLE.is_file()
    assert WHISPER_MODEL.is_file()
    assert JFK_AUDIO.is_file()

    backend = WhisperCLIBackend(
        executable_path=WHISPER_EXECUTABLE,
        model_path=WHISPER_MODEL,
        timeout_seconds=120,
    )

    assert backend.is_configured()

    return SpeechRecognitionEngine(
        backend=backend
    )


def recognize_jfk_audio():
    """
    Run the real JFK audio through whisper.cpp.
    """

    speech = create_real_speech_engine()

    result = speech.recognize_file(
        JFK_AUDIO
    )

    assert result["status"] == (
        "recognized"
    )

    text = result["text"]

    assert isinstance(
        text,
        str
    )

    assert text.strip()

    assert (
        "fellow Americans" in text
    )

    assert (
        "what your country can do for you"
        in text
    )

    return result


def create_single_hypothesis_engine():
    """
    Create a bounded hypothesis planner with exactly
    one candidate.

    Using one hypothesis here is intentional.

    The purpose of this integration test is to verify
    prediction learning for the SAME hypothesis across
    two cycles, rather than testing hypothesis exploration.
    """

    hypothesis_engine = HypothesisEngine(
        max_hypotheses=1
    )

    return HypothesisPlanningEngine(
        hypothesis_engine=hypothesis_engine
    )


def create_real_speech_cognitive_engine(
    transcription
):
    """
    Create a CognitiveExperimentEngine configured for
    real speech-derived learning.
    """

    planner = (
        create_single_hypothesis_engine()
    )

    engine = CognitiveExperimentEngine(
        hypothesis_planner=planner
    )

    experiment = (
        RealSpeechOutcomeExperiment(
            transcription
        )
    )

    engine.experiment_loop.experiment = (
        experiment
    )

    return engine, experiment


def test_real_whisper_recognizes_jfk_audio():
    """
    Verify that real whisper.cpp recognizes the real
    JFK sample audio.
    """

    result = recognize_jfk_audio()

    assert result["status"] == (
        "recognized"
    )

    assert isinstance(
        result["text"],
        str
    )

    assert result["text"].strip()


def test_real_whisper_output_enters_cognitive_perception():
    """
    Verify that the real Whisper transcription crosses
    the speech-recognition boundary and enters perception.
    """

    recognition = recognize_jfk_audio()

    pipeline = CognitivePipeline()

    observation = pipeline.perceive_text(
        recognition["text"]
    )

    assert observation["status"] == (
        "observation_created"
    )

    assert (
        observation["data"]["text"]
        == recognition["text"]
    )


def test_real_speech_to_perception_preserves_transcription():
    """
    Verify that the exact transcription produced by
    whisper.cpp is preserved by the perception layer.
    """

    recognition = recognize_jfk_audio()

    pipeline = CognitivePipeline()

    observation = pipeline.perceive_text(
        recognition["text"]
    )

    assert observation["status"] == (
        "observation_created"
    )

    assert (
        observation["data"]["text"]
        == recognition["text"]
    )


def test_real_speech_pipeline_configuration():
    """
    Verify the cognitive pipeline configuration after
    real speech has entered perception.
    """

    recognition = recognize_jfk_audio()

    pipeline = CognitivePipeline()

    observation = pipeline.perceive_text(
        recognition["text"]
    )

    assert observation["status"] == (
        "observation_created"
    )

    configuration = (
        pipeline.get_configuration()
    )

    assert configuration["perception"] == (
        "PerceptionEngine"
    )

    assert configuration["prediction"] == (
        "PredictionEngine"
    )

    assert configuration["difference"] == (
        "DifferenceEngine"
    )

    assert configuration["learning"] == (
        "LearningEngine"
    )


def test_real_speech_reaches_prediction():
    """
    Verify that the observation produced from real
    Whisper speech can enter the prediction stage.
    """

    recognition = recognize_jfk_audio()

    pipeline = CognitivePipeline()

    observation = pipeline.perceive_text(
        recognition["text"]
    )

    prediction = pipeline.predict(
        observation
    )

    assert prediction["status"] == (
        "predicted"
    )

    assert "prediction" in prediction


def test_real_speech_reaches_difference_and_learning():
    """
    Verify the complete cognitive path:

    Real speech
        ↓
    Whisper
        ↓
    Perception
        ↓
    Prediction
        ↓
    Explicit actual outcome
        ↓
    Difference
        ↓
    Learning

    The actual outcome is intentionally supplied by
    the test. It is not generated by Whisper or the
    cognitive pipeline.
    """

    recognition = recognize_jfk_audio()

    pipeline = CognitivePipeline()

    actual = {
        "text": recognition["text"]
    }

    result = pipeline.run_with_actual(
        actual=actual,
        text=recognition["text"]
    )

    assert result["status"] == (
        "completed"
    )

    assert (
        result["observation"]["status"]
        == "observation_created"
    )

    assert (
        result["prediction"]["status"]
        == "predicted"
    )

    assert (
        result["comparison"]["status"]
        == "compared"
    )

    assert (
        result["learning"]["status"]
        == "learned"
    )

    assert (
        result["comparison"]["actual"]
        == actual
    )

    assert "difference" in (
        result["comparison"]
    )

    assert "result" in (
        result["learning"]
    )


def test_real_speech_learning_changes_next_prediction():
    """
    Step 64-B

    Prove that learning from a real Whisper-derived
    experiment outcome changes the prediction in the
    NEXT cycle for the SAME hypothesis.

    Flow:

    Real Whisper transcription
        ↓
    Numeric observation derived from transcription
        ↓
    First prediction
        ↓
    Explicit observed outcome
        ↓
    Prediction error
        ↓
    Adaptive hypothesis learning
        ↓
    Second prediction
        ↓
    Prediction changed

    The observed outcome does NOT depend on the prediction.
    """

    recognition = recognize_jfk_audio()

    transcription = recognition["text"]

    assert isinstance(
        transcription,
        str
    )

    assert transcription.strip()

    engine, experiment = (
        create_real_speech_cognitive_engine(
            transcription
        )
    )

    observation = len(
        transcription
    )

    expected_actual = (
        len(transcription)
        + 20
    )

    first_result = engine.run_cycle(
        goal_state={
            "goal": "continue_observation"
        },
        observation=observation
    )

    assert first_result["status"] == (
        "completed"
    )

    first_prediction = (
        first_result["prediction"]
    )

    first_actual = (
        first_result["actual"]
    )

    first_difference = (
        first_result["difference"]
    )

    selected_hypothesis = (
        first_result[
            "selected_hypothesis"
        ]
    )

    hypothesis_name = (
        selected_hypothesis[
            "hypothesis"
        ]
    )

    assert isinstance(
        hypothesis_name,
        str
    )

    assert first_prediction == (
        observation
    )

    assert first_actual == (
        expected_actual
    )

    assert first_difference == (
        expected_actual
        - observation
    )

    assert experiment.received_hypothesis == (
        selected_hypothesis
    )

    first_learning = (
        first_result[
            "hypothesis_prediction_learning"
        ]
    )

    assert first_learning["status"] == (
        "learned"
    )

    first_updated_prediction = (
        first_learning[
            "result"
        ]["prediction"]
    )

    expected_first_update = (
        observation
        + (
            0.5
            * (
                expected_actual
                - observation
            )
        )
    )

    assert first_updated_prediction == (
        expected_first_update
    )

    second_result = engine.run_cycle(
        goal_state={
            "goal": "continue_observation"
        },
        observation=observation
    )

    assert second_result["status"] == (
        "completed"
    )

    second_prediction = (
        second_result["prediction"]
    )

    second_actual = (
        second_result["actual"]
    )

    second_difference = (
        second_result["difference"]
    )

    second_hypothesis = (
        second_result[
            "selected_hypothesis"
        ]
    )

    assert second_hypothesis[
        "hypothesis"
    ] == hypothesis_name

    assert second_actual == (
        expected_actual
    )

    assert second_prediction == (
        first_updated_prediction
    )

    assert second_prediction != (
        first_prediction
    )

    assert second_difference == (
        expected_actual
        - first_updated_prediction
    )

    second_learning = (
        second_result[
            "hypothesis_prediction_learning"
        ]
    )

    assert second_learning[
        "status"
    ] == "learned"

    second_updated_prediction = (
        second_learning[
            "result"
        ]["prediction"]
    )

    expected_second_update = (
        first_updated_prediction
        + (
            0.5
            * (
                expected_actual
                - first_updated_prediction
            )
        )
    )

    assert second_updated_prediction == (
        expected_second_update
    )

    history = engine.get_history()

    assert len(history) == 2

    learned_hypotheses = (
        engine.get_learned_hypotheses()
    )

    assert len(
        learned_hypotheses
    ) >= 1

    learned_names = {
        item["hypothesis"]
        for item in learned_hypotheses
    }

    assert hypothesis_name in (
        learned_names
    )
